force-app/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Display_Price__c.field-meta.xml
<CustomField>
    <fullName>Display_Price__c</fullName>
    <label>Display Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <label>ImageUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sizes__c.field-meta.xml
<CustomField>
    <fullName>Sizes__c</fullName>
    <label>Sizes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XS</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
            <value>
                <fullName>XXL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductService.cls
public with sharing class ProductService {
	@AuraEnabled(cacheable=true)
	public static List<Product2> getProducts(
		String name,
		FilterWrapper filtersData
	) {
		String nameLike = '%' + name + '%';

		String query = 'SELECT Name, ImageUrl__c, Display_Price__c FROM Product2 WHERE Name like :nameLike';

		System.debug('name ' + name);
		System.debug('filtersData ' + filtersData);
		if (filtersData != null) {
			if (
				filtersData.families != null &&
				filtersData.families.size() > 0
			) {
				String[] families = filtersData.families;
				query += ' AND Family IN :families';
			}
			if (filtersData.minPrice != null) {
				Decimal minPrice = filtersData.minPrice;
				query += ' AND Display_Price__c >= :minPrice';
			}
			if (filtersData.maxPrice != null) {
				Decimal maxPrice = filtersData.maxPrice;
				query += ' AND Display_Price__c <= :maxPrice';
			}
			if (String.isNotBlank(filtersData.brand)) {
				String brand = filtersData.brand;
				query += ' AND Brand__c = :brand';
			}
			if (String.isNotBlank(filtersData.brand)) {
				String size = filtersData.size;
				query += ' AND Sizes__c = :size';
			}
		}
		return (Product2[]) Database.query(query);
	}

	public class FilterWrapper {
		@AuraEnabled
		public String[] families { get; set; }

		@AuraEnabled
		public Decimal minPrice { get; set; }

		@AuraEnabled
		public Decimal maxPrice { get; set; }

		@AuraEnabled
		public String brand { get; set; }

		@AuraEnabled
		public String size { get; set; }
	}
}